{% set name = "george" %}
{% set version = "0.3.1" %}
{% set sha256 = "175f1a8022430adab8bf8e5e0ffc3941e5f48ca831bd9460e69716cc2820e628" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record record.txt  # [not win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pybind11
    - numpy
    - scipy  # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - setuptools  # [win]
    - vs2015_runtime  # [win]

test:
  imports:
    - george

about:
  home: https://github.com/dfm/george
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fast and flexible Gaussian Process regression in Python'
  doc_url: http://george.readthedocs.io/
  dev_url: https://github.com/dfm/george

extra:
  recipe-maintainers:
    - hellovenkat
    - scopatz
    - dfm
