{% set name = "george" %}
{% set version = "0.3.0" %}
{% set sha256 = "dba83ad0c085f9aaaa4a93287124c96fd82d5b5c0429932842b32aa4344168d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/g/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record record.txt  # [not win]

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - pybind11
    - numpy x.x

  run:
    - python
    - numpy x.x
    - scipy
    - setuptools  # [win]
    - vs2015_runtime  # [win]

test:
  imports:
    - george

about:
  home: https://github.com/dfm/george
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fast and flexible Gaussian Process regression in Python'
  doc_url: http://george.readthedocs.io/
  dev_url: https://github.com/dfm/george

extra:
  recipe-maintainers:
    - hellovenkat
    - scopatz
    - dfm
