travis:
  secure:
    BINSTAR_TOKEN: V2YFvuWyh/ee1vMZYe1ewLIcpUJ/HTo3/H9qxtsi/k9JBDFpWsuhtpwzvgIeSGZrRd0MP7j9y6nC5k4BJEk1gEhD16tWoa+C7SbuQstgoLYIQRHc7DgTZqNMIHSKJB+4zpj/i2hoT7uCEk+BRusBHItNKxcIzs543Z9RSIBpJPrVhJHRLih6CSfMjslZX9mxnjMVyDio1yLAFre2H0VAs4Nn1PCt4GqNPheRS1WQP4oQqK70NSZhS4J3lv2nhCEdtSY+Id+Gy++MWkyGPy/WXy3dCyYJkhtUFQJFuEVal5aiTB5PWNzCKNlmlXqhvVJYntq8Q2CojxDiYaG9MZ20l6hXlOU6+jVyZHtRz8KrynU/0JtH6pqOqb1aC2U01jD9tUOIAM0NYGExiFVIOJ+Tv1yyay5zFpqdJrfVQaWrugCi5MjxB6JPEzeah2MlAw4h3BtwABBCiX2+NJ9wn9PP55mhSn5Twe7DWhBm7j5mdrVJ3wNsx1NU21UZdEC4EpH5o/rlMpQP+QixQv9E0wL5HvV0L+HAmjb88VWq1g6HWUc5f1+fVMtKk5Uk3i1545/oN8aM8iAawu6JXWlRK5SoPzYc915NLHzKgk+tVKp12TUviXPs4ok/TeNoHEisO9lhyXHK4vOdxrJqHsAv1KzI6/1iwLg/eeGSgpKv/UoSydc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
